name: build + xunit test .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore
    - name: Tests Back.DatReader
      run: dotnet test Back.DatReader.Test --verbosity normal
    - name: Tests File.DatReader
      run: dotnet File.DatReader.Test --verbosity normal
